# Generated by Django 4.2 on 2023-05-18 17:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DispenseRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dispId', models.IntegerField(default=1)),
                ('medicine', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('pillQuantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HumiditySensor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('temperature', models.CharField(max_length=10)),
                ('humidity', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalDispensor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('isDispensing', models.BooleanField(default=False)),
                ('medicine', models.CharField(max_length=100, null=True)),
                ('ultraId', models.IntegerField(default=1000)),
                ('tempId', models.IntegerField(default=1000)),
                ('quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MotionSensor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('motion', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UltrasonicSensor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('distance', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
