# Generated by Django 4.2 on 2023-05-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_alter_dispenserecord_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispenserecord',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
