# Generated by Django 4.2.1 on 2023-05-21 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_medicaldispensor'),
        ('sensors', '0004_alter_dispenserecord_id'),
    ]

    operations = [
    ]
