# Generated by Django 4.2.1 on 2023-05-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_merge_20230522_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldispensor',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
