# Generated by Django 4.2 on 2023-05-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineDetail',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('condition', models.CharField(max_length=100)),
                ('alcohol', models.CharField(max_length=1)),
                ('pregnant', models.CharField(max_length=1)),
                ('rating', models.FloatField(default=0.0)),
                ('rx_otc', models.CharField(max_length=50)),
                ('side_effects', models.TextField()),
            ],
        ),
    ]
