# Generated by Django 4.2 on 2023-05-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_medicinedetail_rating_alter_medicinedetail_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinedetail',
            name='alcohol',
            field=models.CharField(max_length=1),
        ),
    ]
