# Generated by Django 4.2.1 on 2023-05-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_alter_medicinedetail_alcohol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinedetail',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
