# Generated by Django 4.2.1 on 2023-05-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0005_medicinedetail_rx_otc'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinedetail',
            name='side_effects',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
